// <copyright file="GlobalSuppressions.cs" company="Defra">
// Copyright (c) Defra. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Design",
    "CS8618:Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.",
    Justification = "Data Entities are generated by EF Core",
    Scope = "namespaceanddescendants",
    Target = "~N:Lis.Infra.FeatureFlag.Database.Entities")]
